name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: Install parser generators
      run: sudo apt-get update && sudo apt-get install -yq bison flex libfl-dev lcov
    - name: Run tests with coverage
      run: >-
        bazel coverage
        --combined_report=lcov
        --instrumentation_filter=//
        //:naja_verilog_tests
    - name: Prepare project coverage report
      run: |
        lcov \
          --extract bazel-out/_coverage/_coverage_report.dat 'src/*' \
          --output-file coverage.unfiltered.info
        lcov \
          --add-tracefile coverage.unfiltered.info \
          --filter region \
          --output-file coverage.info
        sed -i '/^BR/d' coverage.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
        files: ${{ github.workspace }}/coverage.info
        disable_search: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
