name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}-${{ matrix.os }}
        repository-cache: true
    - name: Install parser generators
      run: |
        brew install bison flex
        echo "$(brew --prefix flex)/bin" >> "$GITHUB_PATH"
        echo "$(brew --prefix bison)/bin" >> "$GITHUB_PATH"
    - name: Build
      run: bazel build //:all
    - name: Test
      run: bazel test //:naja_verilog_tests
