name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: Install parser generators
      run: sudo apt-get update && sudo apt-get install -yq bison flex libfl-dev valgrind
    - name: Build
      run: bazel build //:naja_verilog_tests
    - name: Run tests with Valgrind
      run: >-
        valgrind
        --error-exitcode=1
        --show-leak-kinds=all
        --leak-check=full
        --errors-for-leak-kinds=all
        ./bazel-bin/naja_verilog_tests
